# Generated by Django 5.0.6 on 2024-10-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=100)),
                ('Item_description', models.CharField(max_length=100)),
                ('Item_price', models.IntegerField()),
            ],
        ),
    ]
