# Generated by Django 5.1.2 on 2024-12-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_app', '0004_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Item_image',
            field=models.TextField(),
        ),
    ]
